### ISSUE TITLE
[Submission] Hardhacker的Base16配色方案

### ISSUE THREAD

**Issue by monicfenga** [hardhackerlabs/themes#25]
以下为Hardhacker的[Base16](https://github.com/chriskempson/base16)配色方案，每个颜色符合Base16的建议，免费贡献给贵repo。代码量极少，~~估计我不用单独开repo提交？~~

```yaml
scheme: "HardHacker"
author: "HardHackerLabs(https://github.com/hardhackerlabs/)"
base00: "282433"
base01: "211e2a"
base02: "3f3951"
base03: "938aad"
base04: "938aad"
base05: "eee9fc"
base06: "eee9fc"
base07: "e4dee9"
base08: "e192ef"
base09: "ebde76"
base0A: "b3f4f3"
base0B: "b1f2a7"
base0C: "ebde76"
base0D: "b1baf4"
base0E: "e965a5"
base0F: "938aad"
```

以及CSS变量版本（便于与[Web16](https://github.com/Rotekoppen/web16)结合使用）：

```css
/* HardHacker by HardHackerLabs(https://github.com/hardhackerlabs/) */

:root {
  --base00: #282433;
  --base01: #211e2a;
  --base02: #3f3951;
  --base03: #938aad;
  --base04: #938aad;
  --base05: #eee9fc;
  --base06: #eee9fc;
  --base07: #e4dee9;
  --base08: #e192ef;
  --base09: #ebde76;
  --base0A: #b3f4f3;
  --base0B: #b1f2a7;
  --base0C: #ebde76;
  --base0D: #b1baf4;
  --base0E: #e965a5;
  --base0F: #938aad;
}
```

使用这套配色方案的效果：

![使用这套配色方案的效果](https://github.com/hardhackerlabs/themes/assets/39868412/a46c433a-854a-471c-93c6-2c19be0de4ce)

> ### Base16 简介
> [Base16](https://github.com/chriskempson/base16)的初衷是为了解决代码编辑器中颜色方案不一致的问题，但它的应用远不止于此。这套方案不仅适用于代码编辑器，还可以用于网站和其他用户界面的设计。
> 
> 在Base16中，每种颜色都有特定的用途和意义。例如，深色和浅色的组合可以用于前景和背景，而不同的颜色可以用于表示不同类型的语法元素，如变量、操作符、关键字等。这种一致的颜色方案有助于提高代码的可读性和可维护性。
